-- SQLite
CREATE TABLE LOCATIONS(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  START_DATE DATE,
  END_DATE DATE NOT NULL,
  TOTAL DECIMAL(10, 2) NOT NULL,
  CUSTOMER_ID INTEGER,
  CAR_ID INTEGER,
  EMPLOYEE_ID INTEGER,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
  FOREIGN KEY (CAR_ID) REFERENCES CARS(ID)
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
);

